### PR TITLE
Testing automatic scam link detection

### PR DESCRIPTION
**Pull request by Angry-Pineapple3121**
this is probably extremely broken

[Email] - From KTG6O06U.KTG6O06U@ktg6o06u.us - Denneyjulian Look at my ass_I_ want_your_C*ck Now!💋👅💋F*ck Me Hard🔥_👉_👌_ID:Aan,70
[Email] - From xsicdsbdssheqlbb@fnuyknjzmvsi.trackchance.com.br -  🔞🍆Message For _Denneyjulian_🔥Grow_Your_Penis🍌Up_To "7 Inches"📏 with "🔥African Elongation Ritual🔥"
[Email] - From 6KyDzNx6TfrYNvkzfBkaWQl29zQR3@6kydznx6tfrynvkzfbkawql29zqr3.stepvillage.com - __hey_Denneyjulian__💲(𝟏) 𝐏𝐚𝐲𝐦𝐞𝐧𝐭 𝐬𝐞𝐧𝐭 𝐭𝐨{ Denneyjulian } 💳 𝐖𝐨𝐫𝐭𝐡 $𝟓𝟎𝟎?
[Email] - From DB00OX9E.DB00OX9E@24e87l9a.us - Ž Ž Ž Ž Ž Ž Ž ●💰５００００＄_PAYOUT VERIFICATION⭕️𝗙𝗜𝗡𝗔𝗟 𝗡𝗢𝗧𝗜𝗖𝗘!!!!⭕️𝘾𝙝𝙚𝙘𝙠_𝙮𝙤𝙪𝙧_𝙖𝙘𝙘𝙤𝙪𝙣𝙩 ▶️💰🎁24746_
[Email] - From DIUW5ERG.DIUW5ERG@4ogecde7.us - Ž Ž Ž Ž Ž ⭕️[Pending]⭕️𝗬𝗢𝗨.𝗛𝗔𝗩𝗘.𝗕𝗘𝗘𝗡.𝗣𝗔𝗜𝗗___💲823547💰✅💲Please_confirm_receipt💲💲_96428
[Email] - From a2FCPv6DUSF3eY5sbE@zaft0qq1neizh87bgugk.w6dzanjs2sk2eji.a2fcpv6dusf3ey5sbe.dzoutside.co.com -👉✔️\'𝐄𝐦𝐞𝐫𝐠𝐞𝐧𝐜𝐲_𝐆𝐨𝐯𝐞𝐫𝐧𝐦𝐞𝐧𝐭 𝐀𝐧𝐧𝐨𝐮𝐧𝐜𝐞𝐬 : 𝐀𝐥𝐥 𝐘𝐎𝐮𝐫 𝐃𝐞𝐛𝐭𝐬_𝐇𝐚𝐯𝐞 𝐁𝐞𝐞𝐧 𝐂𝐚𝐧𝐜𝐞𝐥𝐞𝐝\'✔️✔️✔️✔️5168
[Email] - From 09z07eop4m6tcmd@98419.wolf.leadingfoozle.com - Thank Yo͏u Denneyjulian - P͏͏͏͏l͏͏e͏͏a͏͏s͏͏e͏͏ C͏͏o͏͏n͏͏f͏͏i͏͏r͏͏m͏͏ KOHLS FREE $100$ GIFT CARD CODE 😍 🎁

[Info] - Added a total of 33 links to repository /nacrt/SkyblockClient-REPO/blob/main/files/scamlinks.json

✔️ Automatically edited JSON.
✔️ No errors found.

### CODE REVIEW

**Comment by Angry-Pineapple3121** [comment]
its fucking scam detection thats what it is zord

**Comment by Lisenaaaa** [comment]
yeah but wtf is the description

**Comment by nacrt** [comment]
✔️ Works on my machine
✔️ Errors found.

**Comment by MrIDontKNow-hub** [comment]
Relatable

**Comment by Angry-Pineapple3121** [comment]
> yeah but wtf is the description

[came from where] - came from what email - email title/header

**Comment by ghost** [comment]
That’s not the point

EMAIL ADRESSES AREN’T SENT ON DISCORD

**Pull request merged**
