### PR TITLE
did i do this right

### PR DESCRIPTION
**Pull request by MicrocontrollersDev**

### CODE REVIEW

**Comment by Wyvest** [comment]
i think you did it right

**Comment by MicrocontrollersDev** [comment]
https://youtu.be/HGy9i8vvCxk?t=76

**Comment by KTibow** [comment]
if it works then merge it yourself

**Comment by MicrocontrollersDev** [comment]
1. idk if it works
2. need an image for nox mods

**Comment by KTibow** [comment]
beta mods dont need a logo

**Comment by MicrocontrollersDev** [comment]
it's been well over a week if no one says anything I'm merging this later today and hope it doesn't cause issues

**Pull request merged**
