### PR TITLE
I think this works

### PR DESCRIPTION
**Pull request by TymanWasTaken**
I just copy pasted neu-repo validation code

### CODE REVIEW

**Comment by Lisenaaaa** [comment]
wtf is this even for

**Comment by TymanWasTaken** [comment]
> wtf is this even for

So it tells at you if you have invalid json

**Comment by TymanWasTaken** [comment]
Of wait you have invalid JSON anyway this won't work

||Comments go brrrrr||

**Comment by TymanWasTaken** [comment]
uh how exactly are you able to mark it as ready, I specifically tried to make it so you *can't* do that

but ok ig

**Comment by ghost** [comment]
fat L @TymanWasTaken

**Pull request merged**
