### PR TITLE
clarification

### PR DESCRIPTION
**Pull request by ghost**
fuck you

also write a guide cunt
modcore supremacy

### CODE REVIEW

**Comment by koxx12-dev** [comment]
u that xanderlib is modified modcore

**Comment by koxx12-dev** [comment]
u know that*

**Comment by ghost** [comment]
it's not
it's either stolen modcore
or shit

**Comment by koxx12-dev** [comment]
maybe it is stolen

**Comment by koxx12-dev** [comment]
image

**Comment by koxx12-dev** [comment]
proof

**Pull request merged**
