### PR TITLE
Added Dungeon Room Mod guide

### PR DESCRIPTION
**Pull request by ghost**
I think my code implementing the guide will work, keyword "think".

### CODE REVIEW

**Comment by JoeyE2** [comment]
feel i hate to break it to you but nobody else cares about capitalization

**Comment by ghost** [comment]
> feel i hate to break it to you but nobody else cares about capitalization

I made a whole fucking guide
Not a capitalization patch
dipshit

**Comment by JoeyE2** [comment]
nou micro

**Comment by koxx12-dev** [comment]
good guide

**Pull request merged**
