### PR TITLE
Use Prettier for JSON formatting

### PR DESCRIPTION
**Pull request by KTibow**
Rationale:
- Prettier is very widely accepted. It's a standard, and it's always good to conform to standards.
- The current workflow seems to be broken.

### CODE REVIEW

**Comment by nacrt** [comment]
can you remove the changes to any file except validate.yml

**Comment by KTibow** [comment]
well the point of changing `validate.yml` is to change all the other files...

**Comment by nacrt** [comment]
yes, we'll let the bot do the changing after the pr

**Comment by KTibow** [comment]
i have to go to school, i'll fix once home

**Comment by KTibow** [comment]
Bruh

**Comment by KTibow** [comment]
Ready for review.

**Comment by nacrt** [comment]
you have removed the validate json action, was this intentional?

**Comment by KTibow** [comment]
Yes, as Prettier will fail if it can't read a file.

**Comment by KTibow** [comment]
> the Prettier will also fail if it can't find changed json

What do you mean? If it's actually a commit to the branch instead of a pull request, it'll format the code and push the formatted code.

**Comment by KTibow** [comment]
Why though? The existing workflow is kinda unreadable. Let me reiterate how this new workflow would (should) function:
- If it's a PR, it would fail if it doesn't match Prettier style, or it can't read a JSON file. If it doesn't fail, it would show as successful.
- If it's a commit to the `main` branch, it would fail if it couldn't read a JSON file. If it doesn't fail, it would push the formatted JSON.
- If none of these criteria are matched, the workflow wouldn't run.

**Pull request closed without merging**
