### PR TITLE
make sk1er support its own thing

### PR DESCRIPTION
**Pull request by JoeyE2**

### CODE REVIEW

**Comment by JoeyE2** [comment]
welp

**Review by Lisenaaaa — CHANGES_REQUESTED** [review]
why didnt you just copy the code from sk1er, change the values of some things, then paste it in right under it

**Comment by ghost** [comment]
nice one joey

**Comment by JoeyE2** [comment]
bruh

**Comment by ghost** [comment]
> bruh

you do be gamin

**Comment by JoeyE2** [comment]
im so mad

**Comment by ghost** [comment]
> im so mad

I*
jk Zordlan no ban

**Comment by JoeyE2** [comment]
is github still shitting istelf about a space

**Comment by ghost** [comment]
> is github still shitting istelf about a space

yep
nice goin

**Comment by JoeyE2** [comment]
bruh

**Comment by MicrocontrollersDev** [comment]
will be redone

**Pull request closed without merging**
