### PR TITLE
Updated a few responses for botautoresponse.json

### PR DESCRIPTION
**Pull request by iHemoX3**
Corrected the "how to download" response to match the new channels for the server

### CODE REVIEW

**Comment by KTibow** [comment]
looks good, also eventually once we get skyclient.co going we should add it to the bot? idk

**Comment by KTibow** [comment]
wait why did you undo the typo fix

**Comment by iHemoX3** [comment]
> wait why did you undo the typo fix

look in discord

**Comment by iHemoX3** [comment]
pog

**Pull request merged**
