### PR TITLE
Parity

### PR DESCRIPTION
**Pull request by ghost**
STAY. IN. THE. SERVER

### CODE REVIEW

**Comment by KTibow** [comment]
wait why do we also have #319

**Comment by ghost** [comment]
Wyvest has too much short man energy and wrote the same guide twice

**Comment by MicrocontrollersDev** [comment]
wouldn't it make more sense to just remove wyvtils considering wyvest himself no longer supports it and recommends using other mods? it's guess it's still in mods.json but wouldn't it also make sense to remove it from there as well, or is there a different reason for that that I'm not seeing

**Comment by MicrocontrollersDev** [comment]
wyvtils is dead i see no reason to keep the guide updated or this pr open any longer

**Comment by Mqisty** [comment]
>  it's guess it's still in mods.json but wouldn't it also make sense to remove it from there as well, or is there a different reason for that that I'm not seeing

image
(ignore the bottom message i didnt see that)

**Comment by MicrocontrollersDev** [comment]
honestly imo we should remove it there as well. it will never be readded and there’s no archival benefits really. just useless clutter

**Pull request closed without merging**
