### PR TITLE
Update DSM

### PR DESCRIPTION
**Pull request by SufferingSevereBrianDamage**
check dsm #issues-and-support pins

### CODE REVIEW

**Comment by SufferingSevereBrianDamage** [comment]
I don’t blame you for missing because they didn’t even put it in #new-commits smh

**Comment by nacrt** [comment]
well but is it stable

**Comment by SufferingSevereBrianDamage** [comment]
fair, idk i’ll check it out ig

**Comment by SufferingSevereBrianDamage** [comment]
~~wait why would they pin it in their support channel if it isn’t~~

**Comment by Shiggy-dev** [comment]
doesnt crash on startup thats good

**Comment by SufferingSevereBrianDamage** [comment]
<:happey:827600317570220093>

**Comment by Shiggy-dev** [comment]
that actually worked
nice

**Comment by SufferingSevereBrianDamage** [comment]
<:trollgod:887751640852095038>

**Comment by SufferingSevereBrianDamage** [comment]
@nacrt we merge or naw

**Comment by MrIDontKNow-hub** [comment]
nah let the repo live, its acc cool

**Comment by SufferingSevereBrianDamage** [comment]
your morher

**Comment by SufferingSevereBrianDamage** [comment]
mother

**Comment by SufferingSevereBrianDamage** [comment]
check <#742116160186613821> yes

**Comment by BrianDamageALT** [comment]
HELP ME GUYS

**Comment by BrianDamageALT** [comment]
SO MY MOTHER IS SHIT AND TOOK MY PHONE AJSUDNE

**Comment by BrianDamageALT** [comment]
SO SINCE I CANT USE DISCORD ON SCHOOL IPAD
I AM GOING TO COMMUNICATE USING FUCKING GITHUB

**Comment by BrianDamageALT** [comment]
😀😀😀😀😀😀😀😀

**Comment by 8KCoffeeWizard** [comment]
skill issue

**Comment by Shiggy-dev** [comment]
yes

**Comment by Shiggy-dev** [comment]
if you can see this ping me many times

**Comment by MrIDontKNow-hub** [comment]
@koxx12-dev-is-bad

**Comment by ghost** [comment]
but Koxx12 Dev isn’t bad

**Comment by Shiggy-dev** [comment]
:widew:

**Comment by Wyvest** [comment]
> HELP ME GUYS

L

**Comment by Shiggy-dev** [comment]
shush non

**Comment by Wyvest** [comment]
> shush non

shut up nonner?

**Pull request closed without merging**
