### PR TITLE
Update mods.json

### PR DESCRIPTION
**Pull request by JoeyE2**
becuase dg doesent work, hide so unsmart people dont go to #support and ask why it isint working

### CODE REVIEW

**Review by nacrt — CHANGES_REQUESTED** [review]
give it a wearning instead

**Comment by koxx12-dev** [comment]
warning*

**Comment by cyoung06** [comment]
Hmmmmmmmmmmmmmmm

**Comment by koxx12-dev** [comment]
dead commmit

**Comment by koxx12-dev** [comment]
pr*

**Comment by ghost** [comment]
Noo you can’t just close 123

**Comment by koxx12-dev** [comment]
email replies are very pog

**Pull request closed without merging**
