### PR TITLE
update bdsm image to makie it dsm becuase its not 4/1/21 anymore

### PR DESCRIPTION
**Pull request by JoeyE2**

### CODE REVIEW

**Comment by JoeyE2** [comment]
merge my last 2 commits

**Comment by JoeyE2** [comment]
not all 19

**Comment by koxx12-dev** [comment]
@JoeyE2 
remove line 211,216,217 
remove comma in 214,215

**Comment by JoeyE2** [comment]
merge pls

**Comment by koxx12-dev** [comment]
its valid json
U did it :D

**Comment by JoeyE2** [comment]
omg i did it thanks koxx

**Comment by koxx12-dev** [comment]
np

**Comment by koxx12-dev** [comment]
also you need to re-add the things u removed (discord.json)

red = removed

image

**Comment by JoeyE2** [comment]
ok i need to eat gimie like 5 mins

**Comment by koxx12-dev** [comment]
there are still 2 errors

image

**Comment by koxx12-dev** [comment]
remove one quote at 206
and add "]" at the end

**Comment by JoeyE2** [comment]
fixed

**Comment by koxx12-dev** [comment]
ye fixed

**Comment by koxx12-dev** [comment]
make a new pull request

**Comment by koxx12-dev** [comment]
cuz discord.json is outdated

**Comment by JoeyE2** [comment]
then i need to close

**Pull request closed without merging**
