### PR TITLE
Add all of the texture pack makers too credits.txt

### PR DESCRIPTION
**Pull request by JoeyE2**
you know i was just bored please dont bully me

### CODE REVIEW

**Comment by JoeyE2** [comment]
WHAT

**Comment by JoeyE2** [comment]
THIS IS A TXT FILE NOT A JSON ILE WHAT THE FUCK

**Comment by JoeyE2** [comment]
koxx im going to chop your head off

**Comment by koxx12-dev** [comment]
it only errored out
it didnt do anything

**Comment by koxx12-dev** [comment]
so just ignore it

**Pull request merged**
