### PR TITLE
Create creators.josn

### PR DESCRIPTION
**Pull request by JoeyE2**
idk  if this will work buit if it doesent murder me

### CODE REVIEW

**Comment by JoeyE2** [comment]
yessssssssssssss

**Comment by Lisenaaaa** [comment]
nice empty file :omegalul:

**Comment by JoeyE2** [comment]
yes i want you to fill it out becuase im shit at json remember

**Comment by JoeyE2** [comment]
and that means this pr has no use

**Comment by JoeyE2** [comment]
im gonna commit suicide

**Comment by JoeyE2** [comment]
(joking)

**Comment by Lisenaaaa** [comment]
not funny

**Comment by JoeyE2** [comment]
just close it or merge it already

**Comment by JoeyE2** [comment]
ok

**Comment by Lisenaaaa** [comment]
then nacrt will make me add the shit to the bot and what we have is working fine so no

**Comment by JoeyE2** [comment]
do it 
it will make the bot work better
you customers and fellow comrades will be happy

**Comment by nacrt** [comment]
empty file

**Pull request closed without merging**
