### PR TITLE
Add Skyclient Cosemtics

### PR DESCRIPTION
**Pull request by koxx12-dev**

### CODE REVIEW

**Comment by koxx12-dev** [comment]
i cant spell

**Comment by koxx12-dev** [comment]
wait i dont it correctly

**Comment by koxx12-dev** [comment]
forgot about the warning

**Comment by koxx12-dev** [comment]
zord speed

**Comment by Lisenaaaa** [comment]
its the one thing i can do with github on my phone

**Comment by Lisenaaaa** [comment]
i am grammar goddess
the only thing i can do with github on my phone is mess with PRs that other people make

**Comment by koxx12-dev** [comment]
lmao

**Comment by ghost** [comment]
FUCK NO yOU AREN'T YOU LITTLE child

"i"

**Pull request merged**
