### PR TITLE
SO

### PR DESCRIPTION
**Pull request by ghost**
FUCK dungeons guide https://paste.ee/p/GYKly
FUCK SBA
FUCK  people who don't use neu
FUCK GULPON (!!!)

### CODE REVIEW

**Comment by ghost** [comment]
seriously tho

fuck gulponc

**Comment by ghost** [comment]
awwww

**Comment by ghost** [comment]
> awwww

why tho

**Comment by nacrt** [comment]
the descriptions are fine but don't ever go messing with enabled or hidden

**Comment by ghost** [comment]
> the descriptions are fine but don't ever go messing with enabled or hidden

but sba is bad

and minecraft is good 


ok

**Pull request closed without merging**
