### PR TITLE
add blur config

### PR DESCRIPTION
**Pull request by MicrocontrollersDev**
OptiFine changes the path to chat, which means the default blur exclusion does not work. Having the game blur when opening chat, while might look cool, is not intended and may be annoying or distracting. I've only seen one user complain about it but it still needs to be changed. PR because I forgor if you have to do anything more than this :skull:

### CODE REVIEW

**Comment by nacrt** [comment]
this file will get ignored by every installer

**Comment by MicrocontrollersDev** [comment]
Yeah, I figured. I thought maybe that mcdir wasn't hardcoded and just threw it all in, but I couldn't remember.

**Comment by nacrt** [comment]
you're placing a lot of trust on us
either way, github does not give a list of files in any given directory without downloading the whole repository

**Comment by MicrocontrollersDev** [comment]
damn 😔

**Comment by KTibow** [comment]
@MicrocontrollersDev add it to `mods.json`, like [this](https://github.com/nacrt/SkyblockClient-REPO/blob/8dc6c2c7d3b2bbba11eeeee3dca4832f9da701b7/files/mods.json#L66-L69)

**Review by nacrt — CHANGES_REQUESTED** [review]
resolve conflicts

**Comment by MicrocontrollersDev** [comment]
should be good now

ok why it yelling at me

**Pull request merged**
