### PR TITLE
wall pi

### PR DESCRIPTION
**Pull request by Zetvue**

### CODE REVIEW

**Comment by Shiggy-dev** [comment]
why though

**Review by KTibow — APPROVED** [review]
wall pi :+1:

**Comment by Zetvue** [comment]
BRING BACK WALL PI

**Comment by Zetvue** [comment]
SKYE YOU CANT KEEP THIS AWAY FROM US FUCKER

**Comment by Zetvue** [comment]
pi is back, this pr is not needed

**Pull request closed without merging**
