### PR TITLE
bazaar notifier

### PR DESCRIPTION
**Pull request by Wyvest**

### CODE REVIEW

**Comment by KTibow** [comment]
what does it even do again

**Comment by Wyvest** [comment]
> what does it even do again

`"description": "Mod for Hypixel Skyblock that helps with tracking bazaar sell offer and buy order movements."`

**Comment by KTibow** [comment]
someday i should make a flipping mod or smth, except that it would be a lot of work to learn how to render stuff and everything instead of just making a chattriggers module

**Comment by Zetvue** [comment]
fuck you wyvest

**Pull request merged**
