### PR TITLE
added "mods" to cmm

### PR DESCRIPTION
**Pull request by koxx12-dev**

### CODE REVIEW

**Comment by nacrt** [comment]
what does this do
and
remove the empty line

**Comment by koxx12-dev** [comment]
adds mods button to the main menu

**Comment by koxx12-dev** [comment]
button that shows mod list and allows to edit config in game

**Comment by nacrt** [comment]
does this actually work

**Comment by nacrt** [comment]
screenshot

**Comment by koxx12-dev** [comment]
yep i tested it

**Comment by nacrt** [comment]
https://i.imgur.com/eDzKEyM.jpg

**Comment by koxx12-dev** [comment]
image
image

**Pull request merged**
