### PR TITLE
quick question

### PR DESCRIPTION
**Pull request by ghost**
so do we need that code or not

### CODE REVIEW

**Comment by JosephE2** [comment]
ofc we do dumbass

**Comment by ghost** [comment]
but...
why
it's a link to a changelog that goes updated once every decade
it's like an accidental child

**Comment by Lisenaaaa** [comment]
did i leave that in

**Comment by Lisenaaaa** [comment]
joey, we really dont need that code

**Comment by ghost** [comment]
> did i leave that in

What did you leave in?

**Pull request merged**
