### PR TITLE
fix forge

### PR DESCRIPTION
**Pull request by MicrocontrollersDev**
not sure if actually works, cant test for another few hours

the installer jar also has a new name and not sure if it changes anything

### CODE REVIEW

**Comment by nacrt** [comment]
different file name changes everything

**Comment by MicrocontrollersDev** [comment]
can i just rename the file?

**Comment by nacrt** [comment]
don't change the jar at all
just replace the maven links in the json

**Comment by MicrocontrollersDev** [comment]
alright will revert

**Pull request merged**
