### PR TITLE
Revamp mods.json

### PR DESCRIPTION
**Pull request by KTibow**
just consistency stuff
im off to eat + sleep now, lmk what i should change

### CODE REVIEW

**Comment by KTibow** [comment]
Next I wanna validate discord links and other links (not dead).

**Review by nacrt — CHANGES_REQUESTED** [review]
great pr, however shortDesc is never used anywhere
how do you intend it to be used?

**Comment by KTibow** [comment]
for cloudclient updated, where space used will matter and out of date descriptions are unacceptable

**Comment by KTibow** [comment]
duplicate of #332

**Pull request closed without merging**
