### PR TITLE
hide wyvtils

### PR DESCRIPTION
**Pull request by Wyvest**
remove wyvtils as requisite is currently dead

### CODE REVIEW

**Comment by koxx12-dev** [comment]
Just hide it smh

**Comment by Wyvest** [comment]
OH YEAH HOLD UP

**Comment by Wyvest** [comment]
thanks koxx12

**Comment by Shiggy-dev** [comment]
trol

**Comment by SufferingSevereBrianDamage** [comment]
WYVEST ILY

**Comment by Wyvest** [comment]
thanks

**Pull request merged**
