### PR TITLE
I really hope this works

### PR DESCRIPTION
**Pull request by ghost**
I forgot how to JSON

### CODE REVIEW

**Review by Lisenaaaa — CHANGES_REQUESTED** [review]
i have two problems with this pr
1: you forgot a comma in NEUs description smfh, it should be something like `essential modification for playing skyblock, featuring whateverthefuckyouputthere`
2: its only called bdsm as a joke in IDs and shit please dont call it that in the description of the mod

**Comment by ghost** [comment]
fIne

and oh god I missed a coma
I am becoming what I swore to destroy

A casual

**Comment by Lisenaaaa** [comment]
its spelled `comma` smfh bad

**Comment by ghost** [comment]
what the fuck now

**Review by ghost — COMMENTED** [review]
I can't click approve changes

**Comment by ghost** [comment]
help

**Comment by koxx12-dev** [comment]
lmao

**Comment by ghost** [comment]
my ass is thick

my skull is thicker

**Comment by ghost** [comment]
that was not supposed to come out

**Pull request merged**
