### PR TITLE
added Dugeon Rooms (mod)

### PR DESCRIPTION
**Pull request by koxx12-dev**

### CODE REVIEW

**Comment by nacrt** [comment]
we don't have a mod with that id

**Review by nacrt — CHANGES_REQUESTED** [review]
set hidden to true for the mod

**Comment by koxx12-dev** [comment]
fixed

**Review by nacrt — APPROVED** [review]

**Comment by nacrt** [comment]
wait for risk to respond, then we'll add it

**Comment by koxx12-dev** [comment]
:D

**Review by nacrt — CHANGES_REQUESTED** [review]
link the Discord and Github

**Comment by koxx12-dev** [comment]
ok

**Comment by koxx12-dev** [comment]
created #69 
cuz i cant edit this one

**Pull request closed without merging**
