### PR TITLE
Add Skyhanni

### PR DESCRIPTION
**Pull request by koxx12-dev**
DO NOT MERGE YET

### CODE REVIEW

**Comment by hannibal002** [comment]
You could make it a "draft" to make it more clear it should not get merged

**Review by nacrt — APPROVED** [review]

**Review by hannibal002 — APPROVED** [review]

**Comment by Wyvest** [comment]
replace the warning with "SkyHanni requires NEU to function! Installing SkyHanni will also install NEU."

**Comment by koxx12-dev** [comment]
> replace the warning with "SkyHanni requires NEU to function! Installing SkyHanni will also install NEU."

You know it's not a bundle right? It doesn't actually install neu

**Comment by koxx12-dev** [comment]
Oh wait nacrt changed it

**Pull request merged**
