### PR TITLE
Update EvergreenHUD entry

### PR DESCRIPTION
**Pull request by isXander**
Updated the json entry for evergreen to add a description, creator and action tags, also changed evergreen icon to isxander. also moved it up a bit to be next to the other HUD mod

### CODE REVIEW

**Comment by koxx12-dev** [comment]
Looks like u did it correct not like JoshE5
I would suggest adding a warning cuz its in beta

**Comment by koxx12-dev** [comment]
Joey*

**Comment by isXander** [comment]
yah ill add warning now

**Comment by JoeyE2** [comment]
koxx you shut your fucking mouth

**Pull request merged**
