### PR TITLE
nopo changes

### PR DESCRIPTION
**Pull request by MicrocontrollersDev**
idk what any of this means nopo asked me to pr it tho

### CODE REVIEW

**Comment by KTibow** [comment]
please
https://prettier.io/playground/ ([heres a json version](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwC+IA0IIAcYCW0AzsqAIYBOlEA7gApUKkrkA2t5AnqdgEaVyYANZwYAZXIBbOABkCUOMgBm7YnH6CRY8biEKA5shiUArhpBwpfOABNbd2eSgHT5A3ABiESlPIxCF2QQclMYCCwQAAsYKTYAdSiCeGI9MDhxZmSCADdkrmCwYl4QBXVKGHpBAz8VNQsAK2IAD3FDNjgARVMIeDq2dWw9SnLgpuhI3EoFGHiCWxgo5AAOAAYhmnV4wVxgqbhynKVsAEce+Cq8FhDiAFpFOztIyjgzgheq91qkVQGLdSkBGMZn+7TgAEEAtM+GE4PQ4JR5Ip+oMQMQwd1ekofvVsDByHw5gslkgAEx4wQENiGADCECk30sxAArJFTOoACoEli-VE5cwASSgDlg4jA03w4OF4hgXA6KLgaDQQA))

**Comment by MicrocontrollersDev** [comment]
man i thought actions would take care of it

**Comment by KTibow** [comment]
i do not know why actions did not take care of it

**Comment by MicrocontrollersDev** [comment]
just as i was about to do it i see a refresh button in the files changed tab man

**Comment by NopoTheGamer** [comment]
why didnt you make the formatting the same lmao 😭

**Pull request merged**
