### PR TITLE
Deleted useless "hidden":"false"

### PR DESCRIPTION
**Pull request by koxx12-dev**

### CODE REVIEW

**Comment by nacrt** [comment]
why

**Comment by koxx12-dev** [comment]
they are there
and they are useless

**Comment by nacrt** [comment]
i am doing this to torture zord to force the bot to have good code

**Comment by koxx12-dev** [comment]
makes sense

**Comment by Lisenaaaa** [comment]
> i am doing this to torture zord to force the bot to have good code

im like 90% sure that it doesnt care about hidden because of the mods in bundles

**Pull request closed without merging**
