### PR TITLE
hope this wrks

### PR DESCRIPTION
**Pull request by JoeyE2**

### CODE REVIEW

**Comment by JoeyE2** [comment]
bruhh

**Comment by JoeyE2** [comment]
GIIIIIIIIIIIIIIIIIIIIIIIIIITHUUUUUUUUUUUUUUUUUUUUUUB THHERE IS NO FUCKING LINE 217

**Review by JoeyE2 — COMMENTED** [review]
FUCK

**Comment by nacrt** [comment]
> 
> 
> GIIIIIIIIIIIIIIIIIIIIIIIIIITHUUUUUUUUUUUUUUUUUUUUUUB THHERE IS NO FUCKING LINE 217

make one then

**Comment by JoeyE2** [comment]
ok bruh

**Comment by JoeyE2** [comment]
how do i fuck things up so badly

**Comment by MotorGorilla1** [comment]
> how do i fuck things up so badly

I have no idea

**Comment by JoeyE2** [comment]
it tells me colum 8 and then colum 9

**Comment by JoeyE2** [comment]
i give up someone do it for me

**Comment by JoeyE2** [comment]
closed

**Pull request closed without merging**
