### PR TITLE
pre-emptive dungeons guide

### PR DESCRIPTION
**Pull request by ghost**
@rioho 
write that essay now
or I wasted my time

### CODE REVIEW

**Comment by riohorealhk** [comment]
can i fix it

**Comment by ghost** [comment]
thank you micro, very cool

shit patch closed

**Comment by riohorealhk** [comment]
what

**Comment by riohorealhk** [comment]
open it again plz

**Comment by ghost** [comment]
internet troll

seriously though @riohorealhk could you give me links

**Comment by MicrocontrollersDev** [comment]
once dungeonsguide releases and we have consent to add it and the proper stuff is put in please squash and merge, dont just merge.

**Comment by riohorealhk** [comment]
idk but this is an essay
Why should the Dungeons Guide mod get added to SkyClient? 
Dungeons guide is a hypixel skyblock forge modification, which is aimed at dungeons. It is the most advanced and most intelligent dungeons mod. It is a forge mod running on Minecraft version 1.8.9. There are 2 reasons that the mod should be added to the sky client, which I will talk about it below.
First, it is the first mod ever made which includes a secret waypoint. The secret solvers have helped a lot of players when the mod is paid, they even learnt secrets by using our mod. The secret solvers also do not trigger watchdog and aren’t against hypixel’s rules and the recent update of modification guidelines. There are 3 reasons why the secret finder isn’t against hypixel’s rule and isn’t bannable. First, It is not Watchdog detectable since it does not modify player behaviour or packet. Second, it isn’t an esp as we use a static set of coordinates from a corner of the room a player is in. Unlike other “secret waypoint” mod which is just chest and item drop esp. Last, it does not provide any unfair advantages, people who have learnt secret can do much faster than the people following the mod’s pathfinding line.
Second, it has the most advanced dungeons puzzle solvers. Our water solver is the fastest in the hypixel skyblock mod industry. Also, all the puzzles are dynamically calculated, even you broke the silverfish puzzle, it will still show the correct path to move it back to the hole. For the box solver, you can type recalc in chat and it will try to find a solution if u accidentally pressed the wrong button. 
All in all, this mod is the first mod ever made with a secret waypoint that isn’t against any hypixel rules, and have the most advanced dungeons solvers. Therefore, it should be added to SkyClient.

**Comment by 8KCoffeeWizard** [comment]
lmfao you actually wrote an essay

**Comment by nacrt** [comment]
huge L

**Comment by cyoung06** [comment]
lol

**Comment by ghost** [comment]
hey guys

just checking

Wasn't this mod paid

**Comment by riohorealhk** [comment]
It’s gonna be open source in a week sooooooo

> hey guys
>
> just checking
>
> Wasn't this mod paid
>

**Comment by riohorealhk** [comment]
> lmfao you actually wrote an essay

Broooo who wrote that in the readme.md

**Comment by koxx12-dev** [comment]
Me

**Comment by wutisntpog** [comment]
no, i did

**Comment by JosephE2** [comment]
bruhhhhhhhhhhhhhhhhhhhh

**Review by My-Name-Is-Jeff — CHANGES_REQUESTED** [review]
I think this should be closed as it isn't completed

**Review by My-Name-Is-Jeff — APPROVED** [review]

**Comment by nacrt** [comment]
stop putting things above neu

**Comment by riohorealhk** [comment]
should i open my own pr, cuz i cannot write stuff inside here which is very unpog

**Comment by nacrt** [comment]
you are free to do anything 
i will (squash and) merge the pr i like more

**Comment by MicrocontrollersDev** [comment]
dont think this is needed anymore? reopen if it is i guess

**Pull request closed without merging**
