### PR TITLE
ℹ️ Add scam domain - discorcl.click

### PR DESCRIPTION
**Pull request by Angry-Pineapple3121**
➡️ Description
Distributed through Discord group chat (compromised account)

➡️ Domain status:
❌ Offline

### CODE REVIEW

**Comment by Angry-Pineapple3121** [comment]
Hosted @ 95.181.157.84

**Comment by IlluminatiFish** [comment]
> Hosted @ 95.181.157.84

is one of the IPs that always appears in these discord/steam scams others include

95.181.157.36 
194.226.139.115
194.226.139.121
194.226.139.120
194.226.139.123

**Comment by itohatweb** [comment]
There's already a pr for this link btw #201

**Comment by IlluminatiFish** [comment]
> There's already a pr for this link btw #201

Yeah he realised this after lmao

**Pull request closed without merging**
