### PR TITLE
Bump optifine to m6 pre2

### PR DESCRIPTION
**Pull request by PikaFan123**
OptiFine M5 seems to cause some issues on MacOS, namely the game getting stuck on a white screen during launch, so I bumped OptiFine to M6 Preview 2, which fixes this issue.
Source: https://discord.com/channels/771187253937438762/821151183070298174/851538813788749854 on https://discord.gg/fsr

### CODE REVIEW

**Comment by Wyvest** [comment]
> OptiFine M5 seems to cause some issues on MacOS, namely the game getting stuck on a white screen during launch, so I bumped OptiFine to M6 Preview 2, which fixes this issue.
> Source: https://discord.com/channels/771187253937438762/821151183070298174/851538813788749854 on https://discord.gg/fsr

Can you remove the version from the name itself? I don't know why it was there in the first place, but removing it now is a good idea.

**Comment by PikaFan123** [comment]
removed it

**Review by Wyvest — APPROVED** [review]

**Comment by KTibow** [comment]
image

**Comment by RayDeeUx** [comment]
holy fuck @KTibow it's been merged already, take a hint won't ya

history is history

**Comment by KTibow** [comment]
lmao why is everyone reacting negatively to me just sending a screenshot of a previous chat

**Comment by UnderscoreRayless** [comment]
> lmao why is everyone reacting negatively to me just sending a screenshot of a previous chat

It's just ery being ery, never take his word for everyone's word

**Comment by KTibow** [comment]
"everyone" might be a little unrealistic when the only people reacting are sans and ery sure

**Comment by UnderscoreRayless** [comment]
> "everyone" might be a little unrealistic when the only people reacting are sans and ery sure

That is what i just said

**Pull request merged**
