### PR TITLE
add particles enhanced

### PR DESCRIPTION
**Pull request by isXander**

### CODE REVIEW

**Comment by nacrt** [comment]
can you record a video of what your mod does

**Comment by isXander** [comment]
check the forum thread

**Comment by nacrt** [comment]
link

**Comment by isXander** [comment]
[https://hypixel.net/threads/4416018/](https://hypixel.net/threads/4416018/)

**Comment by koxx12-dev** [comment]
@nacrt merge it or no

**Comment by nacrt** [comment]
tf am i looking at

**Comment by nacrt** [comment]
oh

**Comment by nacrt** [comment]
it allows you to decrease particles

**Comment by koxx12-dev** [comment]
> it allows you to decrease particles

kinda it allows to edit paticles
i dont see a ponit in adding this mod
you can only change crit and sharp particles

**Comment by isXander** [comment]
Don't forget the fade feature. Aesthetics.

**Pull request closed without merging**
