### PR TITLE
Add Dungeons Guide

### PR DESCRIPTION
**Pull request by riohorealhk**
This is the official pull request of adding dungeons guide into the SkyblockClient. 
The mod will be open-source on Saturday. 
Official discord of dungeons guide: discord.gg/dg
The essay I wrote (I actually got faked):
Why should the Dungeons Guide mod get added to SkyClient?
Dungeons guide is a hypixel skyblock forge modification, which is aimed at dungeons. It is the most advanced and most intelligent dungeons mod. It is a forge mod running on Minecraft version 1.8.9. There are 2 reasons that the mod should be added to the sky client, which I will talk about it below.
First, it is the first mod ever made which includes a secret waypoint. The secret solvers have helped a lot of players when the mod is paid, they even learned secrets by using our mod. The secret solvers also do not trigger watchdog and aren’t against hypixel’s rules and the recent update of modification guidelines. There are 3 reasons why the secret finder isn’t against hypixel’s rule and isn’t bannable. First, It is not Watchdog detectable since it does not modify player behavior or packet. Second, it isn’t an esp as we use a static set of coordinates from a corner of the room a player is in. Unlike other “secret waypoint” mod which is just chest and item drop esp. Last, it does not provide any unfair advantages, people who have learned secret can do much faster than the people following the mod’s pathfinding line.
Second, it has the most advanced dungeons puzzle solvers. Our water solver is the fastest in the hypixel skyblock mod industry. Also, all the puzzles are dynamically calculated, even you broke the silverfish puzzle, it will still show the correct path to move it back to the hole. For the box solver, you can type recalc in chat and it will try to find a solution if u accidentally pressed the wrong button.
All in all, this mod is the first mod ever made with a secret waypoint that isn’t against any hypixel rules, and have the most advanced dungeons solvers. Therefore, it should be added to SkyClient.

### CODE REVIEW

**Comment by 8KCoffeeWizard** [comment]
why did you include the essay in this pepelaugh

**Comment by riohorealhk** [comment]
Why not

**Comment by koxx12-dev** [comment]
ok very cool essay

**Comment by JosephE2** [comment]
ok cool this is pog

**Review by koxx12-dev — APPROVED** [review]

**Comment by riohorealhk** [comment]
Dungeons Guide is officially released

**Review by nacrt — CHANGES_REQUESTED** [review]
change enabled to false

**Comment by riohorealhk** [comment]
ok will do now

**Comment by nacrt** [comment]
and put it way below optifine

**Review by nacrt — APPROVED** [review]

**Pull request merged**
