### PR TITLE
update from wyvest to qalcyo

### PR DESCRIPTION
**Pull request by Wyvest**

### CODE REVIEW

**Comment by Wyvest** [comment]
ready for review

**Comment by ghost** [comment]
no

**Comment by Wyvest** [comment]
ok

**Comment by nacrt** [comment]
grafik

**Comment by Wyvest** [comment]
> grafik

didn't ask + ratio + xD + i hate myself + why did i forget to change the discord invite + i am idiot

**Comment by MrIDontKNow-hub** [comment]
Denied

**Comment by Shiggy-dev** [comment]
skill issue

**Pull request merged**
