### PR TITLE
Changed DSM to use the crash fix 

### PR DESCRIPTION
**Pull request by 8KCoffeeWizard**
crash = bad

### CODE REVIEW

**Comment by koxx12-dev** [comment]
Add "better" back

**Comment by koxx12-dev** [comment]
I would make this a file check thing but im on mobile

**Comment by 8KCoffeeWizard** [comment]
no better is bad i hoped no one will notice smh

**Comment by koxx12-dev** [comment]
Then I wont merge it

**Comment by koxx12-dev** [comment]
simple

**Comment by 8KCoffeeWizard** [comment]
:weirdchamp: fine

**Pull request merged**
