### PR TITLE
nicknames for packs! wait will this even work

### PR DESCRIPTION
**Pull request by RayDeeUx**

### CODE REVIEW

**Comment by nacrt** [comment]
how about defaultbackport

**Comment by RayDeeUx** [comment]
i'm sure no one will memorize that from a user perspective

**Comment by nacrt** [comment]
> i'm sure no one will memorize that from a user perspective

no you are supposed to add it to the list

**Comment by RayDeeUx** [comment]
> > i'm sure no one will memorize that from a user perspective
> 
> no you are supposed to add it to the list

i think i might need to visit a shrink because i've been shortcircuting my thoughts as of late, the deed has been done @nacrt <@435443705055543306>

**Pull request merged**
