### PR TITLE
Add SimpleHUD and TimerHUD

### PR DESCRIPTION
**Pull request by Wyvest**
Yes, I have gotten permission from Matthew.

### CODE REVIEW

**Comment by koxx12-dev** [comment]
"if you want a mod to be added write a lengthy article on why it should be added, where to get it and how it is related to skyblock"
write it on sc discord

**Comment by koxx12-dev** [comment]
[sc discord](https://discord.gg/VH6fdBYzQQ)

**Comment by Wyvest** [comment]
> "if you want a mod to be added write a lengthy article on why it should be added, where to get it and how it is related to skyblock"
> write it on sc discord

ah sorry i didn't see that, i thought you could just make a pr, i'll close the pr and when nacrt approves i'll make another one

**Comment by koxx12-dev** [comment]
rn this rule i only written on discord
so join it write 20-50 word article on general and maybe it will get approved!

**Comment by ghost** [comment]
We already have a HUD mod tho, why is this here

**Comment by Wyvest** [comment]
> We already have a HUD mod tho, why is this here

i've said this in the discord, but there's already two hud mods, but one is specifically for skyblock and doesn't have many basic hud elements, and the other is a. xander code b. in beta and c. in my testing it gives you less fps lol. simplehud has none of evergreen's problems and just better. functions similar to timerhud don't exist in any mod for 1.8.9 (except for batty's coords plus), so i think it would be cool.

**Comment by isXander** [comment]
> > We already have a HUD mod tho, why is this here
> 
> i've said this in the discord, but there's already two hud mods, but one is specifically for skyblock and doesn't have many basic hud elements, and the other is a. xander code b. in beta and c. in my testing it gives you less fps lol. simplehud has none of evergreen's problems and just better. functions similar to timerhud don't exist in any mod for 1.8.9 (except for batty's coords plus), so i think it would be cool.

A. ?
B. No, version 2 is in beta. It is stable but there is more to add.
C. I have not been able to observe fps drops so if u can't give me evidence in the issue on the github I'm not gonna look into it further.

How is it better?

**Comment by isXander** [comment]
Why can't matt do this himself?

**Comment by Wyvest** [comment]
> > > We already have a HUD mod tho, why is this here
> > 
> > 
> > i've said this in the discord, but there's already two hud mods, but one is specifically for skyblock and doesn't have many basic hud elements, and the other is a. xander code b. in beta and c. in my testing it gives you less fps lol. simplehud has none of evergreen's problems and just better. functions similar to timerhud don't exist in any mod for 1.8.9 (except for batty's coords plus), so i think it would be cool.
> 
> A. ?
> B. No, version 2 is in beta. It is stable but there is more to add.
> C. I have not been able to observe fps drops so if u can't give me evidence in the issue on the github I'm not gonna look into it further.
> 
> How is it better?

a. xander code (ignore this sorry lol)
b. my bad, in the skyclient repo it says its beta software
c. i will post evidence in the issue i made today

overall i think it should be added because variety and a choice between a selection of hud mods, in this case, sbhud, evergreen, minihud, simplehud, and timerhud. i know some people (like myself) like simplehud more because the elements are organized and the gui looks very different from evergreenhud, which has everything upfront. timerhud uses modcore instead of the normal gui. sbhud has a very rpg like look to it and is for skyblock specifically.
also i added simplehud for matthew because i had nothing else to do and wanted to do it and i asked matthew and he said ok
regardless nacrt has said he won't be adding simplehud and timerhud so

**Pull request closed without merging**
