### PR TITLE
* New Hash & fixed Update packs.json

### PR DESCRIPTION
**Pull request by Sean2739**
This is the changes needed to be added. With, I believe, the correct Hash.

### CODE REVIEW

**Comment by nacrt** [comment]
you named the release "Release"?

**Comment by Sean2739** [comment]
> you named the release "Release"?

Yes

**Comment by KTibow** [comment]
You shouldn't.
Version your releases. Don't delete the old ones. That's just standard.

**Comment by Sean2739** [comment]
> You shouldn't. Version your releases. Don't delete the old ones. That's just standard.

Should I just version it and then make a new pull request?

**Comment by KTibow** [comment]
You can edit this one.

**Comment by Sean2739** [comment]
> You can edit this one.

Alright, I went ahead and edited it.

**Comment by MicrocontrollersDev** [comment]
You mistook the screenshot field for the url field.
image
revert this ^
image
replace this link with the new download link ^

**Comment by MicrocontrollersDev** [comment]
went ahead and fixed it myself

**Review by MicrocontrollersDev — APPROVED** [review]

**Comment by MicrocontrollersDev** [comment]
description is kind of vague but that can be changed later. might as well at least get an updated version out

**Pull request merged**
