### PR TITLE
SkyClient Cosmetics 1.0.0

### PR DESCRIPTION
**Pull request by Wyvest**

### CODE REVIEW

**Comment by KTibow** [comment]
> VSync caps your FPS to your current monitor's FPS. Although this can be useful in some cases, most of the time you don't need this.

im not 100% sure but i think on low-end pcs vsync is stopping them from exploding

**Comment by Wyvest** [comment]
> > VSync caps your FPS to your current monitor's FPS. Although this can be useful in some cases, most of the time you don't need this.
> 
> im not 100% sure but i think on low-end pcs vsync is stopping them from exploding

you are wrong

**Comment by KTibow** [comment]
https://letmegooglethat.com/?q=does+vsync+lower+cpu+temp

**Comment by Wyvest** [comment]
> https://letmegooglethat.com/?q=does+vsync+lower+cpu+temp

You are wrong

**Comment by nacrt** [comment]
> https://letmegooglethat.com/?q=does+vsync+lower+cpu+temp

vsync caps the fps to whatever your monitor is
it also checks to make sure that the image on the monitor has passed before pushing the next image
this prevents screen tearing but increases load on the cpu

**Comment by Wyvest** [comment]
Ready for review.

**Pull request merged**
